# run: conda env create --file conda_env_ia_czi.yml
name: imageanalysis_czi
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - conda
  - docutils
  - pip
  - vs2015_runtime
  - wheel
  - setuptools
  - numpy
  - pandas
  - seaborn
  - jupyter
  - widgetsnbextension
  - matplotlib
  - xmltodict
  - ipywidgets
  - lxml
  - openpyxl
  - xlrd
  - xlsxwriter
  - xlwings
  - xlwt
  - dask
  - dask-image
  - zarr
  - pydash
  - scikit-image
  - tifffile
  - scipy
  - autopep8
  - progressbar2
  - imagecodecs
  - pip:
      #- -r file:requirements.txt
      - napari[all]==0.4.7
      - aicsimageio[all]>=3.3.4,<4
      - aicspylibczi>=2.8.0,<4
      - magicgui>=0.2.9, <1
      - mightymosaic>=1.2.3,<2
      - czifile>=2019.7.2
      - apeer-dev-kit>=1.2.2,<2
      - apeer-ometiff-library>=1.7.2,<2
# Create an environmemt
# conda env create --file conda_env_ia_czi.yml

# Update an environment
# conda env update --name imageanalysis_czi --file conda_env_ia_czi.yml --prune

# Remove an environment
# conda remove --name imageanalysis_czi --all

# Show the locations of all versions of Python that are currently in the path
# Windows: where python
# Linux which -a python

