# run: conda env create --file conda_env_ia_czi.yml
name: imageanalysis_czi
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - conda
  - docutils
  - pip
  - vs2015_runtime
  - wheel
  - setuptools
  - numpy
  - pandas
  - seaborn
  - jupyter
  - widgetsnbextension
  - matplotlib
  - xmltodict
  - ipywidgets
  - lxml
  - openpyxl
  - xlrd
  - xlsxwriter
  - xlwings
  - xlwt
  - dask
  - dask-image
  - zarr
  - pydash
  - scikit-image
  - tifffile
  - scipy
  - autopep8
  - progressbar2
  - imagecodecs
  - pip:
      - -r file:requirements.txt
# Create an environmemt
# conda env create --file conda_env_ia_czi.yml

# Update an environment
# conda env update --name imageanalysis_czi --file conda_env_ia_czi.yml --prune

# Remove an environment
# conda remove --name imageanalysis_czi --all

# Show the locations of all versions of Python that are currently in the path
# Windows: where python
# Linux which -a python

